# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$sudo$username\
$all\
"""

# Make prompt a single line
[line_break]
disabled = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[❯](bold red)'
# Disable the package module, hiding it from the prompt completely

# Disable packages from showing in text
[package]
disabled = true

# Username format
[username]
style_user = "bold blue"
style_root = "bold red"
disabled = true
show_always = true

[sudo]
format = '[$symbol]($style)'
disabled = false
symbol = " "
style = "bold red"
